DKDEPEND(openscenegraph osgdb_3dc)
IF(NOT ANDROID)
DKDEPEND(openscenegraph osgdb_3ds)
DKDEPEND(openscenegraph osgdb_ive)
DKDEPEND(openscenegraph osgdb_lwo)
DKDEPEND(openscenegraph osgdb_openflight)
DKDEPEND(openscenegraph osgdb_shp)
ENDIF()
DKDEPEND(openscenegraph osgdb_ac)
DKDEPEND(openscenegraph osgdb_bsp)
DKDEPEND(openscenegraph osgdb_dw)
DKDEPEND(openscenegraph osgdb_dxf)
DKDEPEND(openscenegraph osgdb_logo)
DKDEPEND(openscenegraph osgdb_lws)
DKDEPEND(openscenegraph osgdb_md2)
DKDEPEND(openscenegraph osgdb_obj)
DKDEPEND(openscenegraph osgdb_osg)
DKDEPEND(openscenegraph osgdb_rgb)
DKDEPEND(openscenegraph osgdb_stl)
DKDEPEND(openscenegraph osgdb_x)
DKDEPEND(openscenegraph osgdb_rot)
DKDEPEND(openscenegraph osgdb_scale)
DKDEPEND(openscenegraph osgdb_normals)
DKDEPEND(openscenegraph osgdb_trans)
DKDEPEND(openscenegraph osgTerrain)
DKDEPEND(openscenegraph osgVolume)
DKDEPEND(openscenegraph osgSim)
DKDEPEND(openscenegraph osgFX)
DKDEPEND(openscenegraph osgdb_serializers_osg)
DKDEPEND(openscenegraph osgParticle)
DKDEPEND(openscenegraph osgdb_serializers_osgparticle)
DKDEPEND(openscenegraph osgdb_deprecated_osg)
DKDEPEND(DKOSGWindow)

DKPLUGIN(DKOSGModel)
